### ISSUE TITLE
Can it be used in docker?

### ISSUE THREAD

**Issue by maxgalbu** [sj-i/php-profiler#409] opened 2024-01-17 08:18 UTC
I've tried to point reli to a process running in docker, but this is the error:

```
root@d1461bdcc4fe:/var/www/hs-pricing/reli-prof# ./reli inspector:memory -p 3036

In MemoryReader.php line 92:

  failed to read memory. target_pid=3036, remote_address=0x557bf9a1e000, errno=1
```

**Comment by sj-i** [comment] 2024-01-17 13:55
@maxgalbu 
Hi!
Reli can be used in a docker container.

> errno=1

This indicates that your process doesn't have the permission needed to analyze the target process.
Maybe your container doesn't have the capability to use ptrace.
Try to use `--cap-add=SYS_PTRACE --security-opt="seccomp=unconfined"` on `docker run`.

If you don't want to add the capability to the whole container including other applications, you can also use Reli in a separate container.

https://github.com/reliforp/reli-prof?tab=readme-ov-file#from-docker
> ```
> docker pull reliforp/reli-prof
> docker run -it --security-opt="apparmor=unconfined" --cap-add=SYS_PTRACE --pid=host reliforp/reli-prof
> ```

With `--pid=host`, you can use the pid of the target process in the host pid namespace. If you want to use the pid in the container of the target process, you can use `--pid=container:<container name>`. See the [manual](https://docs.docker.com/engine/reference/run/#pid-settings---pid) for more detail about this `--pid` option.

**Comment by maxgalbu** [comment] 2024-01-17 15:20
This is the result (pricing-availqueue-8.1 is the name of the running container with the wanted process):

```
$ docker run -it --rm --security-opt="apparmor=unconfined" --cap-add=SYS_PTRACE --pid=container:pricing-availqueue-8.1 reliforp/reli-prof inspector:memory -p 14

Fatal error: Uncaught AssertionError: assert($memory_location instanceof ZendStringMemoryLocation) in /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php:660
Stack trace:
#0 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(660): assert(false, 'assert($memory_...')
#1 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(461): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectZendStringPointer(Object(Reli\Lib\Process\Pointer\Pointer), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools))
#2 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(1456): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectZval(Object(Reli\Lib\PhpInternals\Types\Zend\Zval), 94051955327327, Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpInternals\ZendTypeReader), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools), NULL)
#3 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(1649): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectClassConstantsTable(Object(Reli\Lib\PhpInternals\Types\Zend\ZendArray), 94051955327327, Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpInternals\ZendTypeReader), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools), NULL)
#4 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(1515): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectClassDefinition(Object(Reli\Lib\PhpInternals\Types\Zend\ZendClassEntry), 94051955327327, Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpInternals\ZendTypeReader), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools), NULL)
#5 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(1485): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectClassDefinitionPointer(Object(Reli\Lib\Process\Pointer\Pointer), 94051955327327, Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpInternals\ZendTypeReader), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools), NULL)
#6 /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php(360): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectClassTable(Object(Reli\Lib\PhpInternals\Types\Zend\V80\ZendArray), 94051955327327, Object(Reli\Lib\Process\Pointer\RemoteProcessDereferencer), Object(Reli\Lib\PhpInternals\ZendTypeReader), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocation\MemoryLocations), Object(Reli\Lib\PhpProcessReader\PhpMemoryReader\ContextPools), NULL)
#7 /app/src/Command/Inspector/MemoryCommand.php(83): Reli\Lib\PhpProcessReader\PhpMemoryReader\MemoryLocationsCollector->collectAll(Object(Reli\Lib\Process\ProcessSpecifier), Object(Reli\Inspector\Settings\TargetPhpSettings\TargetPhpSettings), 94051930082496, 94051930084256, NULL)
#8 /app/vendor/symfony/console/Command/Command.php(326): Reli\Command\Inspector\MemoryCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /app/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /app/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Reli\Command\Inspector\MemoryCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/reli(56): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /app/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php on line 660
```

**Comment by sj-i** [comment] 2024-01-17 16:07
@maxgalbu 

Hmm. Reli first found something other than string in a memory address of the target process, then found a reference to the same address as a string value of a class constant. This can be caused by a bug in Reli, but it's also possible that the state of the target process is actually corrupted by a bug in an extension or the interpreter. A use of a dangling pointer in the interpreter can cause such error.

What is the state of the target process? Seems to be running correctly?

Anyway, if you want to get the memory usage of the target process, you can try to use a modified version of Reli.
For example, first clone Reli, and then comment out the [lines collecting class constants](https://github.com/reliforp/reli-prof/blob/0.11.2/src/Lib/PhpProcessReader/PhpMemoryReader/MemoryLocationsCollector.php#L1649-L1658) at all.

Then build the docker image of the modified version of Reli and use it, like this.

```bash
clone git@github.com:reliforp/reli-prof.git
cd reli-prof
# edit MemoryLocationsCollector
docker build -t reli-prof-mod .
docker run -it --rm --security-opt="apparmor=unconfined" --cap-add=SYS_PTRACE --pid=container:pricing-availqueue-8.1 reli-prof-mod inspector:memory -p 14
```

**Comment by maxgalbu** [comment] 2024-01-18 08:15
the process is running fine, apart from the memory leak somewhere
among all the other extensions, I'm using [Phalcon](https://github.com/phalcon/cphalcon)
anyway, with the modified reli it works, thanks!

**Comment by maxgalbu** [comment] 2024-01-18 16:17
New error:

```
In MemoryReader.php line 92:

  failed to read memory. target_pid=14, remote_address=0x1, errno=14
```

**Comment by sj-i** [comment] 2024-01-18 17:32
@maxgalbu
Hi!

To solve the problem, we need more detailed information. How to reproduce the problem, and of course a backtrace would be helpful. If there isn't a backtrace, try `-vvv` as an option to Reli.

Also, please open another issue, as the question about using Reli with Docker has probably been resolved.

I close this for now.

**Closed as completed by sj-i** 2024-01-18 17:32 UTC

**Comment by oleg-filiutsich** [comment] 2024-03-07 10:01
```
# ./reli i:trace -- php -r "sleep(5);" -vvv
PHP 8.2.13 (cli) (built: Nov 27 2023 22:36:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies

In ProcessMemoryByteReader.php line 47:
                          
  [OutOfBoundsException]  
                          

inspector:trace [-p|--pid PID] [-d|--depth [DEPTH]] [-s|--sleep-ns [SLEEP-NS]] [-r|--max-retries [MAX-RETRIES]] [-S|--stop-process [STOP-PROCESS]] [--php-regex [PHP-REGEX]] [--libpthread-regex [LIBPTHREAD-REGEX]] [--zts-globals-regex [ZTS-GLOBALS-REGEX]] [--php-version [PHP-VERSION]] [--php-path [PHP-PATH]] [--libpthread-path [LIBPTHREAD-PATH]] [-t|--template [TEMPLATE]] [-o|--output OUTPUT] [--] [<cmd> [<args>...]]


```

**Comment by sj-i** [comment] 2024-03-07 12:30
@oleg-filiutsich 
Hi! Thanks for the report! Could you try it again with the last option `-vvv` putting before `--` ?

Also, if you open a new issue for this bug report, I would be happy because the current issue template has fields for writing information about the target process and the executing process, and this information is useful for solving the problem (The target and the execution environment are the same in this case though).
